name: CI

on:
  push:
    branches:
      - 'main'
      - 'release/**'
      - 'v*.*.*'
      - '*.*.*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  version-consistency:
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/reusable-version-consistency.yml
    with:
      source-repository: ${{ github.repository }}
      repository-ref: ${{ github.sha }}
    secrets: inherit

  backend:
    needs: [version-consistency]
    if: github.actor != 'dependabot[bot]'
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-backend.yml
    with:
      python-version: "3.12"
      working-directory: "backend"

  frontend:
    needs: [version-consistency]
    if: github.actor != 'dependabot[bot]'
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/reusable-frontend.yml
    with:
      working-directory: "frontend"
    secrets: inherit

  sonarcloud:
    needs: [backend, frontend]
    if: github.actor != 'dependabot[bot]'
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/reusable-sonarcloud.yml
    secrets: inherit
