name: Scheduled Mutation Testing

on:
  schedule:
    - cron: '0 5 * * 1,4'
  workflow_dispatch:

permissions: {}

jobs:
  mutation-testing:
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-mutation-testing.yml
    with:
      min-score: 70

  frontend-mutation-testing:
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-frontend-mutation-testing.yml
